'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Boxes,Plus,Library,Sparkles,MessageSquare,Monitor,Smartphone,Save,Check,Send,LayoutGrid,Cloud,LoaderCircle,Play,RefreshCw,Pencil,Rocket} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {examples,exampleHtml} from '@/lib/examples';
import {sandboxDocument} from '@/lib/sandbox';
type Message={role:'user'|'assistant';content:string};
type MiniApp={id:string;title:string;description:string;html:string;messages:Message[];kind:'ai'|'example';updated?:number};
type Summary=Omit<MiniApp,'html'|'messages'>;
type Context={id:string;saved:boolean;data:Record<string,unknown>;version:number;queue:Promise<unknown>};
async function api(path:string,options?:RequestInit){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options?.headers}});const b=await r.json() as any;if(!r.ok)throw new Error(b.error||'操作未完成，請再試一次。');return b}
function NavButton(props:React.ComponentProps<typeof SidebarMenuButton>){const {setOpenMobile}=useSidebar();return <SidebarMenuButton {...props} onClick={e=>{props.onClick?.(e);setOpenMobile(false)}}/>}
function NewButton({onClick,disabled}:{onClick:()=>void;disabled:boolean}){const {setOpenMobile}=useSidebar();return <button className="new-btn" disabled={disabled} onClick={()=>{onClick();setOpenMobile(false)}}><Plus size={18}/>建立新程式</button>}
export default function Studio(){
 const [view,setView]=useState<'studio'|'library'|'run'>('studio'),[prompt,setPrompt]=useState(''),[active,setActive]=useState<MiniApp|null>(null),[messages,setMessages]=useState<Message[]>([]),[apps,setApps]=useState<Summary[]>([]),[saved,setSaved]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[libraryError,setLibraryError]=useState(''),[libraryLoading,setLibraryLoading]=useState(true),[aiReady,setAiReady]=useState<boolean|null>(null),[signedIn,setSignedIn]=useState<boolean|null>(null),[name,setName]=useState('我的工作空間'),[saveDialog,setSaveDialog]=useState(false),[title,setTitle]=useState(''),[device,setDevice]=useState('desktop'),[dataStatus,setDataStatus]=useState('尚未建立程式');
 const iframe=useRef<HTMLIFrameElement>(null),bottom=useRef<HTMLDivElement>(null),ctx=useRef<Context|null>(null),actions=useRef<any>({}),busyRef=useRef(false);
 const token=useMemo(()=>`${active?.id||'empty'}-${Math.random().toString(36).slice(2)}`,[active?.id,active?.html]);
 const documentHtml=useMemo(()=>active?sandboxDocument(active.html,token):'',[active?.html,token]);
 async function status(){try{const b=await api('/api/status');setAiReady(b.aiReady);setSignedIn(b.signedIn);if(b.name)setName(b.name)}catch{setAiReady(false)}}
 async function loadLibrary(){setLibraryLoading(true);setLibraryError('');try{const b=await api('/api/apps');setApps(b.apps)}catch(e){setLibraryError((e as Error).message)}finally{setLibraryLoading(false)}}
 useEffect(()=>{status();loadLibrary();const id=new URLSearchParams(location.search).get('app');if(id)openApp(id,'run')},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages,busy]);
 function url(id?:string){history.replaceState(null,'',id?`?app=${encodeURIComponent(id)}`:location.pathname)}
 function newApp(){if(busyRef.current||saving)return;setActive(null);setMessages([]);setPrompt('');setSaved(false);setDirty(false);setError('');setView('studio');ctx.current=null;setDataStatus('尚未建立程式');url()}
 function openExample(id:string){if(busyRef.current||saving)return;const example=examples.find(e=>e.id===id);if(!example)return;const app:MiniApp={id:crypto.randomUUID(),title:example.title,description:example.description,html:exampleHtml(id),messages:[{role:'assistant',content:'這是可直接操作的範例程式。你可以先試用，儲存後就能再次開啟；接上 AI 後，也能用對話調整。'}],kind:'example'};ctx.current={id:app.id,saved:false,data:{},version:0,queue:Promise.resolve()};setActive(app);setMessages(app.messages);setSaved(false);setDirty(true);setView('studio');setPrompt('');setError('');setDataStatus('草稿資料 · 儲存程式後保留');url()}
 async function openApp(id:string,destination:'studio'|'run'='run'){if(busyRef.current||saving)return;busyRef.current=true;setBusy(true);setError('');try{const [a,s]=await Promise.all([api(`/api/apps/${encodeURIComponent(id)}`),api(`/api/apps/${encodeURIComponent(id)}/state`)]);ctx.current={id,saved:true,data:s.data,version:s.version,queue:Promise.resolve()};setActive(a.app);setMessages(a.app.messages);setSaved(true);setDirty(false);setPrompt('');setView(destination);setDataStatus('雲端資料已載入');url(id);return true}catch(e){setError((e as Error).message);toast.error((e as Error).message);return false}finally{busyRef.current=false;setBusy(false)}}
 async function generate(){if(!prompt.trim()||busyRef.current||saving)return;const requestPrompt=prompt.trim();busyRef.current=true;setBusy(true);setError('');try{const b=await api('/api/generate',{method:'POST',body:JSON.stringify({prompt:requestPrompt,messages,html:active?.html})});const nextMessages:Message[]=[...messages,{role:'user',content:requestPrompt},{role:'assistant',content:b.message}];const app:MiniApp={id:active?.id||crypto.randomUUID(),title:b.title,description:b.description,html:b.html,messages:nextMessages,kind:'ai'};if(!ctx.current)ctx.current={id:app.id,saved:false,data:{},version:0,queue:Promise.resolve()};setActive(app);setMessages(nextMessages);setDirty(true);setPrompt('');if(!ctx.current.saved)setDataStatus('草稿資料 · 儲存程式後保留')}catch(e){setError((e as Error).message)}finally{busyRef.current=false;setBusy(false)}}
 async function persist(c:Context,data:Record<string,unknown>){const b=await api(`/api/apps/${encodeURIComponent(c.id)}/state`,{method:'PUT',body:JSON.stringify({data,version:c.version})});c.version=b.version}
 async function save(){if(!active||!title.trim()||saving||busyRef.current)return;setSaving(true);setError('');const c=ctx.current!;try{await c.queue;const b=await api('/api/apps',{method:'POST',body:JSON.stringify({...active,title:title.trim(),messages})});c.saved=true;setSaved(true);setActive(b.app);setDirty(false);url(active.id);try{await persist(c,c.data);setDataStatus('雲端資料已儲存')}catch(e){setDataStatus('資料儲存失敗');setError((e as Error).message)}setSaveDialog(false);toast.success('已存入我的程式庫');loadLibrary()}catch(e){setError((e as Error).message);toast.error((e as Error).message)}finally{setSaving(false)}}
 async function retryState(){const c=ctx.current;if(!c?.saved)return;try{await c.queue;await persist(c,c.data);setDataStatus('雲端資料已儲存');setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{function post(payload:any){iframe.current?.contentWindow?.postMessage({channel:'room',token,...payload},'*')}
 function message(event:MessageEvent){const m=event.data;if(event.source!==iframe.current?.contentWindow||!m||m.channel!=='room'||m.token!==token)return;const c=ctx.current;if(!c)return;if(m.type==='ready'){post({type:'init',data:c.data});return}if(m.type==='error'){setError('程式執行遇到問題：'+String(m.message).slice(0,180));return}if(m.type!=='set'||typeof m.requestId!=='string')return;if(!m.data||typeof m.data!=='object'||Array.isArray(m.data)||JSON.stringify(m.data).length>100000){post({type:'result',requestId:m.requestId,error:'資料超過可儲存的範圍。'});return}c.data=m.data;const data=m.data;setDataStatus(c.saved?'資料儲存中…':'草稿資料 · 儲存程式後保留');c.queue=c.queue.catch(()=>{}).then(async()=>{try{if(c.saved)await persist(c,data);if(ctx.current===c)setDataStatus(c.saved?'雲端資料已儲存':'草稿資料 · 儲存程式後保留');post({type:'result',requestId:m.requestId,saved:c.saved})}catch(e){if(ctx.current===c){setDataStatus('資料儲存失敗');setError((e as Error).message)}post({type:'result',requestId:m.requestId,error:(e as Error).message})}})}window.addEventListener('message',message);return()=>window.removeEventListener('message',message)},[token]);
 actions.current={openApp,list:()=>api('/api/apps'),busy:()=>busyRef.current||saving};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'list_saved_apps',title:'列出我的程式',description:'Read the current signed-in user’s saved mini-app library.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input:any){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');const b=await actions.current.list();return {apps:b.apps.map((a:Summary)=>({id:a.id,title:a.title}))}}},{name:'open_saved_app',title:'開啟已儲存程式',description:'Open an existing user-owned mini-app for use; does not create or modify an app.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:any){if(!input||typeof input.id!=='string'||!/^[-a-zA-Z0-9]{10,80}$/.test(input.id)||Object.keys(input).length!==1)throw new Error('Expected a saved app ID');if(actions.current.busy())throw new Error('An operation is already in progress');const ok=await actions.current.openApp(input.id,'run');if(!ok)throw new Error('Unable to open saved app');return {id:input.id,view:'run'}}}];for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const signIn=<a className="primary-btn inline-flex" href="/signin-with-chatgpt?return_to=/" target="_top">登入並開啟程式庫</a>;
 return <SidebarProvider style={{'--sidebar-width':'232px'} as React.CSSProperties}><Toaster theme="light" position="bottom-right"/>
 <Sidebar className="studio-sidebar"><SidebarHeader><div className="brand"><span className="brand-mark"><Boxes size={22}/></span><div>造物間<small>MAKE ROOM</small></div></div><NewButton onClick={newApp} disabled={busy||saving}/></SidebarHeader><SidebarContent><SidebarMenu><SidebarMenuItem><NavButton isActive={view==='studio'||view==='run'} onClick={()=>setView('studio')}><MessageSquare/>創作工作室</NavButton></SidebarMenuItem><SidebarMenuItem><NavButton isActive={view==='library'} onClick={()=>{setView('library');loadLibrary();url()}}><Library/>我的程式庫<span className="library-count">{apps.length}</span></NavButton></SidebarMenuItem></SidebarMenu><div className="side-label">最近儲存</div><SidebarMenu>{apps.slice(0,5).map(app=><SidebarMenuItem key={app.id}><NavButton onClick={()=>openApp(app.id)} disabled={busy||saving}><span className="tiny-app"><LayoutGrid size={14}/></span><span className="truncate">{app.title}</span></NavButton></SidebarMenuItem>)}</SidebarMenu>{!apps.length&&<p className="side-empty">你的第一個小程式<br/>會出現在這裡。</p>}</SidebarContent><SidebarFooter><div className="side-note"><Cloud size={18}/><div>雲端程式庫<small>儲存一次，之後隨時打開</small></div></div><div className="profile"><span>我</span><div className="profile-name">{name}<small>{signedIn?'已登入工作空間':'登入後可儲存程式'}</small></div></div></SidebarFooter></Sidebar>
 <main className="studio-main"><header className="topbar"><div><SidebarTrigger className="mobile-trigger"/><span>{view==='library'?'我的程式庫':'創作工作室'}</span><span className="slash">/</span><span className="muted truncate">{view==='library'?'所有程式':active?.title||'新程式'}</span></div><button className="pill" onClick={status} title="重新檢查 AI 連線"><Sparkles size={14}/>{aiReady===null?'確認 AI 連線中':aiReady?'AI 生成已連接':'AI 生成待連接'}</button></header>
 {view==='library'?<div className="library-page"><div className="library-heading"><div><span className="eyebrow">YOUR OWN LITTLE APPS</span><h1>把好用的想法，留在這裡。</h1><p>你建立的程式，隨時打開、接著使用。</p></div><button className="primary-btn" onClick={newApp}><Plus size={17}/>建立新程式</button></div>{libraryLoading?<div className="app-grid">{[1,2,3].map(i=><Skeleton key={i} className="h-52 rounded-xl"/>)}</div>:libraryError?<div className="notice error-notice"><p>{libraryError}</p>{signedIn===false?signIn:<button className="secondary-btn" onClick={loadLibrary}>重新載入</button>}</div>:apps.length?<div className="app-grid">{apps.map(app=><article className="app-card" key={app.id}><div className="app-card-top"><span className="app-card-icon"><LayoutGrid size={23}/></span><span className="mini-tag">{app.kind==='ai'?'AI 生成':'範例程式'}</span></div><h2>{app.title}</h2><p>{app.description}</p><span className="app-date">{app.updated?new Date(app.updated).toLocaleDateString('zh-TW'):''} 儲存</span><div className="app-card-actions"><button onClick={()=>openApp(app.id)} disabled={busy||saving}><Play size={15}/>開啟使用</button><button onClick={()=>openApp(app.id,'studio')} disabled={busy||saving} aria-label={'調整 '+app.title}><Pencil size={16}/></button></div></article>)}</div>:<div className="library-empty"><Library size={36}/><h2>還沒有儲存的程式</h2><p>從一個需求開始，或先試試下方的範例。</p><button className="primary-btn" onClick={newApp}>建立第一個程式</button></div>}<div className="example-heading"><h2>先試用一個小程式</h2><span className="meta">可操作範例 · 非 AI 即時生成</span></div><div className="app-grid">{examples.map((e,i)=><button className={'example-card tone-'+i} key={e.id} onClick={()=>openExample(e.id)} disabled={busy||saving}><span className="mini-tag">{e.category}</span><h3>{e.title}</h3><p>{e.description}</p><span><Play size={14}/>開啟範例</span></button>)}</div></div>:<div className={'workspace '+(view==='run'?'run-workspace':'')}>
 {view!=='run'&&<section className="conversation"><div className="section-heading"><span><Sparkles size={19}/>和 AI 一起建立</span><span className="meta">{active?'接著調整':'新對話'}</span></div><div className="chat-body">{!messages.length?<><div className="intro-mark"><Sparkles size={26}/></div><h1>今天想做什麼？</h1><p className="intro-copy">說說你需要的工具。從一個想法開始，變成你可以每天使用的小程式。</p><div className="examples"><span className="eyebrow">從這些想法開始</span>{examples.map((e,i)=><div className="example-row" key={e.id}><button onClick={()=>setPrompt(e.prompt)} disabled={busy}><span className={'example-icon tone-'+i}><LayoutGrid size={17}/></span><span>{e.title}<small>{e.description}</small></span><Plus size={16}/></button><button className="try-example" onClick={()=>openExample(e.id)} disabled={busy||saving}>試用範例</button></div>)}</div></>:messages.map((m,i)=><div key={i} className={'chat-message '+m.role}>{m.role==='assistant'&&<span className="assistant-avatar"><Sparkles size={16}/></span>}<div>{m.role==='assistant'&&<span className="message-label">{active?.kind==='example'?'範例助手':'造物 AI'}</span>}<p>{m.content}</p>{m.role==='assistant'&&i===messages.length-1&&<span className="generated-label"><Check size={14}/>{active?.kind==='example'?'範例已開啟':'程式已生成，請在右側試用'}</span>}</div></div>)}{busy&&<div className="thinking" role="status"><LoaderCircle size={17} className="spin"/>{active?'正在處理程式…':'正在建立程式…'}</div>}<div ref={bottom}/></div>{aiReady===false&&<div className="ai-notice"><span>AI 尚未連接，先試用範例。</span><button onClick={status} aria-label="重新檢查 AI 連線"><RefreshCw size={14}/></button></div>}{signedIn===false&&<div className="signin-notice">{signIn}</div>}<form className="composer" onSubmit={e=>{e.preventDefault();generate()}}><textarea aria-label="描述你想建立的程式" placeholder={active?'告訴 AI，還想怎麼調整…':'例如：做一個幫我記錄每天開銷的工具…'} value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={5000} disabled={busy||saving} onKeyDown={e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();generate()}}}/><div><span>⌘ / Ctrl + Enter 送出</span><button className="send-btn" aria-label="送出需求" disabled={!prompt.trim()||busy||saving}>{busy?<LoaderCircle size={18} className="spin"/>:<Send size={18}/>}</button></div></form><p className="composer-note">生成後可以繼續對話，調整介面與功能。</p></section>}
 <section className="canvas"><div className="canvas-toolbar"><Tabs value="preview"><TabsList><TabsTrigger value="preview"><Monitor size={15}/>{view==='run'?'使用程式':'即時預覽'}</TabsTrigger></TabsList></Tabs><div className="canvas-actions"><div className="device-picker"><button className={device==='desktop'?'selected':''} onClick={()=>setDevice('desktop')} aria-label="桌面預覽" aria-pressed={device==='desktop'}><Monitor size={17}/></button><button className={device==='mobile'?'selected':''} onClick={()=>setDevice('mobile')} aria-label="手機預覽" aria-pressed={device==='mobile'}><Smartphone size={17}/></button></div>{view==='run'?<button onClick={()=>setView('studio')}><Pencil size={16}/>繼續調整</button>:<button onClick={()=>{setTitle(active?.title||'');setSaveDialog(true)}} disabled={!active||busy||saving} className={dirty?'save-ready':''}><Save size={16}/>{saved?(dirty?'儲存變更':'程式已儲存'):'儲存程式'}</button>}</div></div>{error&&<div className="error-banner" role="alert"><span>{error}</span>{dataStatus==='資料儲存失敗'&&<button onClick={retryState}>重試儲存資料</button>}<button onClick={()=>setError('')} aria-label="關閉錯誤提示">×</button></div>}{active?<><div className="app-preview-heading"><span>{active.title}</span><span className="meta">{dirty?'尚有未儲存的變更':'已存入程式庫'} · {active.kind==='ai'?'AI 生成':'範例程式'}</span></div><div className={'canvas-space has-app '+(device==='mobile'?'mobile-preview':'')}><iframe ref={iframe} key={token} title={active.title+' 可操作介面'} srcDoc={documentHtml} sandbox="allow-scripts allow-forms" referrerPolicy="no-referrer" onLoad={()=>iframe.current?.contentWindow?.postMessage({channel:'room',token,type:'init',data:ctx.current?.data||{}},'*')}/></div></>:<div className="canvas-space"><div className="empty-preview"><div className="preview-symbol"><Boxes size={42}/></div><h2>讓你的想法，有自己的介面</h2><p>在左側描述需求，程式預覽會出現在這裡。</p><div className="flow"><span><MessageSquare size={16}/>聊想法</span><span className="flow-line"/><span><Monitor size={16}/>試用程式</span><span className="flow-line"/><span><Check size={16}/>存起來</span></div></div></div>}<footer className="canvas-footer"><span className="data-status"><Cloud size={13}/>{dataStatus}</span>{active&&saved&&<button onClick={()=>{setView('run');url(active.id)}} disabled={busy||saving}><Rocket size={13}/>開啟使用</button>}{!active&&<span>每個小程式，都能再次打開使用</span>}</footer></section></div>}
 </main><Dialog open={saveDialog} onOpenChange={o=>{if(!saving)setSaveDialog(o)}}><DialogContent><DialogHeader><DialogTitle>{saved?'儲存程式變更':'留住這個小程式'}</DialogTitle><DialogDescription>儲存介面、功能與目前的資料，之後從「我的程式庫」再次開啟。</DialogDescription></DialogHeader><label className="save-label" htmlFor="app-title">程式名稱</label><input id="app-title" className="title-input" value={title} onChange={e=>setTitle(e.target.value)} maxLength={60} autoFocus disabled={saving}/>{error&&<p className="dialog-error" role="alert">{error}</p>}<DialogFooter><button className="secondary-btn" onClick={()=>setSaveDialog(false)} disabled={saving}>取消</button><button className="primary-btn" onClick={save} disabled={!title.trim()||saving}>{saving?<LoaderCircle size={16} className="spin"/>:<Save size={16}/>}儲存到程式庫</button></DialogFooter></DialogContent></Dialog></SidebarProvider>
}
